2024-12-24 14:29:16,576 - ERROR - __main__ - Exception occured during program running :
Traceback (most recent call last):
  File "/home/lihz/workspace/npu-monitor/npu_monitor/main.py", line 25, in main
    monitor.run()
  File "/home/lihz/workspace/npu-monitor/npu_monitor/npu_monitor.py", line 160, in run
    self.display_npu_info(npu_data)
  File "/home/lihz/workspace/npu-monitor/npu_monitor/npu_monitor.py", line 129, in display_npu_info
    usage_bar = create_progressbar(npu.aicore_usage, BAR_WIDTH)
AttributeError: 'NpuData' object has no attribute 'aicore_usage'
2024-12-24 14:29:55,526 - ERROR - __main__ - Exception occured during program running :
Traceback (most recent call last):
  File "/home/lihz/workspace/npu-monitor/npu_monitor/main.py", line 25, in main
    monitor.run()
  File "/home/lihz/workspace/npu-monitor/npu_monitor/npu_monitor.py", line 160, in run
    self.display_npu_info(npu_data)
  File "/home/lihz/workspace/npu-monitor/npu_monitor/npu_monitor.py", line 129, in display_npu_info
    usage_bar = create_progressbar(npu.aicore_used, BAR_WIDTH)
  File "/home/lihz/workspace/npu-monitor/npu_monitor/utils.py", line 59, in create_progressbar
    bar = "█" * filled_width + "-" * (width - filled_width)
OverflowError: cannot fit 'int' into an index-sized integer
2024-12-24 14:30:41,120 - ERROR - __main__ - Exception occured during program running :
Traceback (most recent call last):
  File "/home/lihz/workspace/npu-monitor/npu_monitor/main.py", line 25, in main
    monitor.run()
  File "/home/lihz/workspace/npu-monitor/npu_monitor/npu_monitor.py", line 160, in run
    self.display_npu_info(npu_data)
  File "/home/lihz/workspace/npu-monitor/npu_monitor/npu_monitor.py", line 129, in display_npu_info
    usage_bar = create_progressbar(npu.aicore_used, BAR_WIDTH)
  File "/home/lihz/workspace/npu-monitor/npu_monitor/utils.py", line 59, in create_progressbar
    bar = "█" * filled_width + "-" * (width - filled_width)
OverflowError: cannot fit 'int' into an index-sized integer
2024-12-24 14:31:02,699 - ERROR - __main__ - Exception occured during program running :
Traceback (most recent call last):
  File "/home/lihz/workspace/npu-monitor/npu_monitor/main.py", line 25, in main
    monitor.run()
  File "/home/lihz/workspace/npu-monitor/npu_monitor/npu_monitor.py", line 160, in run
    self.display_npu_info(npu_data)
  File "/home/lihz/workspace/npu-monitor/npu_monitor/npu_monitor.py", line 129, in display_npu_info
    usage_bar = create_progressbar(npu.aicore_used, BAR_WIDTH)
  File "/home/lihz/workspace/npu-monitor/npu_monitor/utils.py", line 59, in create_progressbar
    bar = "█" * filled_width + "-" * (width - filled_width)
OverflowError: cannot fit 'int' into an index-sized integer
2024-12-24 14:33:22,002 - ERROR - __main__ - Exception occured during program running :
Traceback (most recent call last):
  File "/home/lihz/workspace/npu-monitor/npu_monitor/main.py", line 25, in main
    monitor.run()
  File "/home/lihz/workspace/npu-monitor/npu_monitor/npu_monitor.py", line 160, in run
    self.display_npu_info(npu_data)
  File "/home/lihz/workspace/npu-monitor/npu_monitor/npu_monitor.py", line 129, in display_npu_info
    usage_bar = create_progressbar(npu.aicore_used, BAR_WIDTH)
  File "/home/lihz/workspace/npu-monitor/npu_monitor/utils.py", line 58, in create_progressbar
    filled_width = int(percent / 100 * width)
TypeError: unsupported operand type(s) for /: 'str' and 'int'
